### PR TITLE
Update GPG build scripts

### PR DESCRIPTION
**Pull request by skalee**
GPG build scripts have been through an overhaul recently. Use their freshest versions as of https://github.com/riboseinc/gpg-build-scripts/commit/bbb47b53bac87dcc85a88104b0d6037e699393af.

### CODE REVIEW

**Comment by skalee** [comment]
There are two approaches to bring GPG install scripts to this repository:

1. Simply copy required build scripts from https://github.com/riboseinc/gpg-build-scripts repo
2. Use Git submodules

I'm okay with both, whatever you find more maintainable. Currently, this pull request demonstrates the latter.

Submodules are probably slightly easier to manage and update. But since we talk about just two scripts, it doesn't matter much.

cc @ronaldtse @ribose-jeffreylau

**Comment by ribose-jeffreylau** [comment]
@skalee I suppose being a submodule would make it easier to track version differences?  Copying might just be a bit more error-prone.

**Comment by skalee** [comment]
Then it's merged.

**Comment by ronaldtse** [comment]
Thanks @skalee !

**Pull request merged**
